onlyBuiltDependencies:
  - esbuild
  - "@parcel/watcher"

packageExtensions:
  sass-embedded:
    peerDependencies:
      source-map-js: "*"
    peerDependenciesMeta:
      source-map-js:
        optional: true
